version: '3'

services:
  pg:
    image: postgres:13.2
    environment:
      POSTGRES_DB: EventCounter_development
      POSTGRES_USER: EventCounter
      POSTGRES_PASSWORD: dev
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
